# Generated by Django 4.0.1 on 2022-01-19 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(blank=True, choices=[('Présentiel', 'Présentiel'), ('Visio', 'Visio')], max_length=200, null=True)),
                ('stage_name', models.CharField(blank=True, max_length=200, null=True)),
                ('start_date', models.DateField(blank=True, max_length=200, null=True)),
                ('end_date', models.DateField(blank=True, max_length=200, null=True)),
                ('place', models.CharField(blank=True, max_length=200, null=True)),
                ('teacher', models.CharField(blank=True, max_length=200, null=True)),
                ('organization1', models.CharField(blank=True, max_length=200, null=True)),
                ('org_comment1', models.CharField(blank=True, max_length=200, null=True)),
                ('organization2', models.CharField(blank=True, max_length=200, null=True)),
                ('org_comment2', models.CharField(blank=True, max_length=200, null=True)),
                ('organization3', models.CharField(blank=True, max_length=200, null=True)),
                ('org_comment3', models.CharField(blank=True, max_length=200, null=True)),
                ('formation1', models.CharField(blank=True, max_length=200, null=True)),
                ('for_comment1', models.CharField(blank=True, max_length=200, null=True)),
                ('formation2', models.CharField(blank=True, max_length=200, null=True)),
                ('for_comment2', models.CharField(blank=True, max_length=200, null=True)),
                ('formation3', models.CharField(blank=True, max_length=200, null=True)),
                ('for_comment3', models.CharField(blank=True, max_length=200, null=True)),
                ('formation4', models.CharField(blank=True, max_length=200, null=True)),
                ('for_comment4', models.CharField(blank=True, max_length=200, null=True)),
                ('formation5', models.CharField(blank=True, max_length=200, null=True)),
                ('for_comment5', models.CharField(blank=True, max_length=200, null=True)),
                ('formation6', models.CharField(blank=True, max_length=200, null=True)),
                ('for_comment6', models.CharField(blank=True, max_length=200, null=True)),
                ('teacher1', models.CharField(blank=True, max_length=200, null=True)),
                ('tea_comment1', models.CharField(blank=True, max_length=200, null=True)),
                ('teacher2', models.CharField(blank=True, max_length=200, null=True)),
                ('tea_comment2', models.CharField(blank=True, max_length=200, null=True)),
                ('teacher3', models.CharField(blank=True, max_length=200, null=True)),
                ('tea_comment3', models.CharField(blank=True, max_length=200, null=True)),
                ('teacher4', models.CharField(blank=True, max_length=200, null=True)),
                ('tea_comment4', models.CharField(blank=True, max_length=200, null=True)),
                ('appreciation1', models.CharField(blank=True, max_length=200, null=True)),
                ('ap_comment1', models.CharField(blank=True, max_length=200, null=True)),
                ('appreciation2', models.CharField(blank=True, max_length=200, null=True)),
                ('ap_comment2', models.CharField(blank=True, max_length=200, null=True)),
                ('recommendation1', models.CharField(blank=True, max_length=200, null=True)),
                ('recommendation2', models.CharField(blank=True, max_length=200, null=True)),
                ('other_formation1', models.CharField(blank=True, max_length=200, null=True)),
                ('other_formation2', models.CharField(blank=True, max_length=200, null=True)),
                ('other_formation_comment', models.CharField(blank=True, max_length=200, null=True)),
                ('other_formation_type1', models.CharField(blank=True, max_length=200, null=True)),
                ('other_formation_type2', models.CharField(blank=True, max_length=200, null=True)),
                ('other_formation_type_comment', models.CharField(blank=True, max_length=200, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('function', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('company', models.CharField(blank=True, max_length=200, null=True)),
                ('company_activity', models.CharField(blank=True, max_length=200, null=True)),
                ('total_company', models.CharField(blank=True, max_length=200, null=True)),
                ('total_establishment', models.CharField(blank=True, max_length=200, null=True)),
                ('election_date', models.DateField(blank=True, max_length=200, null=True)),
                ('find', models.CharField(blank=True, max_length=200, null=True)),
                ('find_comment', models.CharField(blank=True, max_length=200, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
