# Generated by Django 4.0.1 on 2022-01-19 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='other_formation1',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='other_formation_type1',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='recommendation1',
        ),
    ]
